version: '3.8'

services:
  smaugx-host:
    image: smaugx-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - smaugx-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: smaugx
      POSTGRES_PASSWORD: smaugx
      POSTGRES_DB: smaugx
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - smaugx-network

networks:
  smaugx-network: