version: '3.8'

services:
  smaugx-host:
    image: smaugx-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CONNECTION_STRING: "Host=127.0.0.1;Port=5432;Username=smaugx;Password=smaugx;Database=smaugx;Pooling=true;"
    networks:
      - smaugx-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: smaugx
      POSTGRES_PASSWORD: smaugx
      POSTGRES_DB: smaugx
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smaugx -d smaugx"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smaugx-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  smaugx-network:

volumes:
  postgres_data: