version: '3.8'

services:
  smaugx-host:
    image: smaugx-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      CONNECTION_STRING: "Host=127.0.0.1;Port=5432;Username=smaugx;Password=smaugx;Database=smaugx;Pooling=true;"
    networks:
      - smaugx-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: smaugx
      POSTGRES_PASSWORD: smaugx
      POSTGRES_DB: smaugx
    networks:
      - smaugx-network

networks:
  smaugx-network: